networks:
  api-server:

services:
  db:
    restart: unless-stopped
    image: postgres:17.2
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=sss-computing
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ../sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ../sql/:/sql/
    ports:
      - 8081:5432
    networks:
      - api-server

  api:
    restart: unless-stopped
    build:
      context: ./api-server
      args:
        - GITHUB_TOKEN=$GITHUB_TOKEN
        - API_SERVER_TAG=internal_v0.2.1
        - SSS_COMPUTING_STRENGTH_TAG=1.1.1-Sofia
    ports:
      - 8080:8080
    networks:
      - api-server

  client:
    build:
      context: ./client
      args:
        - GITHUB_TOKEN=$GITHUB_TOKEN
        - SSS_COMPUTING_CLIENT_TAG=1.0.1
    deploy:
      replicas: 0
    environment:
      DISPLAY: ${DISPLAY}
    network_mode: host
